singularity exec ~/spike/software/lnctools.sif run-featurecounts.R -a transcript_id --strandSpecific 2 -b ../bam/ZM_AM_R1.bam -g genes.gtf -o ZM_AM_R1 1>ZM_AM_R1.log 2>&1 &
singularity exec ~/spike/software/lnctools.sif run-featurecounts.R -a transcript_id --strandSpecific 2 -b ../bam/ZM_AM_R2.bam -g genes.gtf -o ZM_AM_R2 1>ZM_AM_R2.log 2>&1 &
singularity exec ~/spike/software/lnctools.sif run-featurecounts.R -a transcript_id --strandSpecific 2 -b ../bam/ZM_AM_R3.bam -g genes.gtf -o ZM_AM_R3 1>ZM_AM_R3.log 2>&1 &
singularity exec ~/spike/software/lnctools.sif run-featurecounts.R -a transcript_id --strandSpecific 2 -b ../bam/ZM_DR_R1.bam -g genes.gtf -o ZM_DR_R1 1>ZM_DR_R1.log 2>&1 &
singularity exec ~/spike/software/lnctools.sif run-featurecounts.R -a transcript_id --strandSpecific 2 -b ../bam/ZM_DR_R2.bam -g genes.gtf -o ZM_DR_R2 1>ZM_DR_R2.log 2>&1 &
singularity exec ~/spike/software/lnctools.sif run-featurecounts.R -a transcript_id --strandSpecific 2 -b ../bam/ZM_DR_R3.bam -g genes.gtf -o ZM_DR_R3 1>ZM_DR_R3.log 2>&1 &
singularity exec ~/spike/software/lnctools.sif run-featurecounts.R -a transcript_id --strandSpecific 2 -b ../bam/ZM_FM_R1.bam -g genes.gtf -o ZM_FM_R1 1>ZM_FM_R1.log 2>&1 &
singularity exec ~/spike/software/lnctools.sif run-featurecounts.R -a transcript_id --strandSpecific 2 -b ../bam/ZM_FM_R2.bam -g genes.gtf -o ZM_FM_R2 1>ZM_FM_R2.log 2>&1 &
singularity exec ~/spike/software/lnctools.sif run-featurecounts.R -a transcript_id --strandSpecific 2 -b ../bam/ZM_FM_R3.bam -g genes.gtf -o ZM_FM_R3 1>ZM_FM_R3.log 2>&1 &
singularity exec ~/spike/software/lnctools.sif run-featurecounts.R -a transcript_id --strandSpecific 2 -b ../bam/ZM_GP_R1.bam -g genes.gtf -o ZM_GP_R1 1>ZM_GP_R1.log 2>&1 &
singularity exec ~/spike/software/lnctools.sif run-featurecounts.R -a transcript_id --strandSpecific 2 -b ../bam/ZM_GP_R2.bam -g genes.gtf -o ZM_GP_R2 1>ZM_GP_R2.log 2>&1 &
singularity exec ~/spike/software/lnctools.sif run-featurecounts.R -a transcript_id --strandSpecific 2 -b ../bam/ZM_GP_R3.bam -g genes.gtf -o ZM_GP_R3 1>ZM_GP_R3.log 2>&1 &
singularity exec ~/spike/software/lnctools.sif run-featurecounts.R -a transcript_id --strandSpecific 2 -b ../bam/ZM_IM_R1.bam -g genes.gtf -o ZM_IM_R1 1>ZM_IM_R1.log 2>&1 &
singularity exec ~/spike/software/lnctools.sif run-featurecounts.R -a transcript_id --strandSpecific 2 -b ../bam/ZM_IM_R2.bam -g genes.gtf -o ZM_IM_R2 1>ZM_IM_R2.log 2>&1 &
singularity exec ~/spike/software/lnctools.sif run-featurecounts.R -a transcript_id --strandSpecific 2 -b ../bam/ZM_IM_R3.bam -g genes.gtf -o ZM_IM_R3 1>ZM_IM_R3.log 2>&1 &
singularity exec ~/spike/software/lnctools.sif run-featurecounts.R -a transcript_id --strandSpecific 2 -b ../bam/ZM_PP_R1.bam -g genes.gtf -o ZM_PP_R1 1>ZM_PP_R1.log 2>&1 &
singularity exec ~/spike/software/lnctools.sif run-featurecounts.R -a transcript_id --strandSpecific 2 -b ../bam/ZM_PP_R2.bam -g genes.gtf -o ZM_PP_R2 1>ZM_PP_R2.log 2>&1 &
singularity exec ~/spike/software/lnctools.sif run-featurecounts.R -a transcript_id --strandSpecific 2 -b ../bam/ZM_PP_R3.bam -g genes.gtf -o ZM_PP_R3 1>ZM_PP_R3.log 2>&1 &
